export { FlowExecutionError, NodeExecutionError, GraphCycleError, UnknownNodeTypeError, AbortedError, UnknownToolError, HITLTimeoutError } from './errors'
export { LLMClient } from './llm-client'
export type { ILLMClient, ChatMessage, ChatOptions, ToolCallResult, LLMStructuredResponse, ToolDefinition } from './llm-client'
export { EventBus } from './events'
export type { RuntimeEvent, NodeStartEvent, NodeCompleteEvent, NodeErrorEvent, TokenChunkEvent, FlowPausedEvent, FlowCompleteEvent, FlowErrorEvent } from './events'
export { FlowGraph } from './graph'
export { FlowState } from './state'
export { ToolRegistry, createExecutionContext } from './context'
export type { ExecutionContext, ToolDef, FlowFunction, FunctionRegistry, MemoryAdapter } from './context'
export { resolveTemplate, resolveValue } from './template'
export { evaluateExpr } from './expr'
export { FlowRuntime } from './runtime'
export type { ExecutorOutput, ExecutorFn } from './executors/index'
export { getExecutor, registerExecutor, unregisterExecutor } from './executors/index'
// Phase 3 exports
export { InMemoryAdapter } from './memory/in-memory'
export { IndexedDBAdapter } from './memory/indexeddb'
export type { MemoryResult } from './memory/adapter'
export { BUILT_IN_TOOLS } from './tools/built-ins'
export { DexieExperienceStore } from './experience-store/dexie-experience-store'
export type { DexieExperienceStoreOptions } from './experience-store/dexie-experience-store'
export { requestPersistentStorage } from './storage-persistence'
// Filesystem-backed storage (Tauri desktop / CLI) — see plans/tauri_desktop_plan.html Phase 3
export { FileSystemAdapter } from './memory/filesystem'
export type { FileSystemAdapterOptions } from './memory/filesystem'
export type { FsBackend } from './memory/fs-backend'
export { FileSystemExperienceStore } from './experience-store/filesystem-experience-store'
export type { FileSystemExperienceStoreOptions } from './experience-store/filesystem-experience-store'
export { InMemoryReminderStore } from './reminders/reminder-store'
export type { ReminderStore, ReminderRecord } from './reminders/reminder-store'
