import type { FlowSpec } from './schema'

export const EXAMPLE_FLOWS: { label: string; spec: FlowSpec }[] = [
  {
    label: 'RAG Agent',
    spec: {
      spec_version: '0.2.0',
      id: 'rag-agent-flow',
      name: 'RAG Agent',
      description: 'Semantic retrieval from a vector store, grounded LLM answer generation, and Q&A caching.',
      runtime_hints: { preferred_adapter: 'langgraph', compatible: ['langgraph', 'mastra', 'crewai', 'microsoft_agent_framework'] },
      model_defaults: { model: 'gpt-4o-mini', embedding_model: 'text-embedding-3-small' },
      state_schema: {
        type: 'object',
        properties: {
          question:          { type: 'string', description: 'User input question' },
          retrieved_chunks:  { type: 'array',  description: 'Relevant document chunks', reducer: 'replace' },
          formatted_context: { type: 'string', description: 'Chunks as a context string' },
          answer:            { type: 'string', description: 'Generated grounded answer' },
        },
        required: ['question'],
      },
      memory_stores: {
        knowledge_base: { type: 'vector', description: 'Product documentation', backend: 'qdrant', connection_env: 'QDRANT_URL', embedding_model: 'text-embedding-3-small', dimensions: 1536, scope: 'global' },
        qa_cache:       { type: 'key_value', description: 'Q&A pair cache', backend: 'redis', connection_env: 'REDIS_URL', scope: 'thread' },
      },
      nodes: [
        { id: 'start',          type: 'input',        label: 'User question',          output_schema: { type: 'object', properties: { question: { type: 'string' } } }, position: { x: 60,  y: 220 } },
        { id: 'retrieve',       type: 'memory_read',  label: 'Semantic retrieval',     store_id: 'knowledge_base', retrieval_mode: 'semantic', query_expr: '$.state.question', top_k: 5, min_score: 0.72, output_key: 'retrieved_chunks', position: { x: 368, y: 220 } },
        { id: 'format_context', type: 'transform',    label: 'Format chunks',          mode: 'fn_ref', fn_ref: '@canvas/flows-rag/formatChunks', position: { x: 676, y: 220 } },
        { id: 'generate',       type: 'llm_call',     label: 'Generate grounded answer', system_prompt: 'You are a helpful assistant. Answer using only the provided context.', prompt_template: 'Context:\n{{$.state.formatted_context}}\n\nQuestion: {{$.state.question}}\n\nAnswer:', model_params: { temperature: 0.1, max_tokens: 512 }, output_key: 'answer', position: { x: 984, y: 220 } },
        { id: 'cache_qa',       type: 'memory_write', label: 'Cache Q&A pair',         store_id: 'qa_cache', key_expr: '$.state.question', value_expr: '$.state.answer', write_mode: 'upsert', position: { x: 1292, y: 220 } },
        { id: 'done',           type: 'output',       label: 'Return answer',          position: { x: 1600, y: 220 } },
      ],
      edges: [
        { type: 'direct', from: 'start',          to: 'retrieve' },
        { type: 'direct', from: 'retrieve',       to: 'format_context' },
        { type: 'direct', from: 'format_context', to: 'generate' },
        { type: 'direct', from: 'generate',       to: 'cache_qa' },
        { type: 'direct', from: 'cache_qa',       to: 'done' },
      ],
      flow_config: {
        checkpoint: { enabled: true, backend: 'postgres', connection_env: 'DATABASE_URL' },
        streaming:  { enabled: true, mode: 'tokens' },
        telemetry:  { enabled: true, provider: 'langfuse', project: 'rag-agent', trace_all_nodes: true },
      },
    },
  },
  {
    label: 'Content Moderation + HITL',
    spec: {
      spec_version: '0.2.0',
      id: 'content-moderation-hitl-flow',
      name: 'Content Moderation with HITL Escalation',
      description: 'Classify content severity, auto-approve low/medium, escalate high to human reviewer.',
      runtime_hints: { preferred_adapter: 'mastra', compatible: ['mastra', 'langgraph', 'crewai', 'microsoft_agent_framework'] },
      model_defaults: { model: 'gpt-4o' },
      state_schema: {
        type: 'object',
        properties: {
          content:          { type: 'string', description: 'User-submitted content to moderate' },
          classification:   { type: 'object', description: 'LLM classification result' },
          reviewer_outcome: { type: 'object', description: 'Human reviewer decision' },
          response:         { type: 'string', description: 'Final moderation response' },
        },
        required: ['content'],
      },
      nodes: [
        { id: 'start',        type: 'input',            label: 'Incoming content',              output_schema: { type: 'object', properties: { content: { type: 'string' } } }, position: { x: 60,  y: 280 } },
        { id: 'classify',     type: 'llm_call',         label: 'Classify severity',             system_prompt: 'You are a content moderation classifier. Classify severity as low, medium, or high. Respond with JSON only.', prompt_template: 'Classify this content:\n\n{{$.state.content}}', model_params: { temperature: 0 }, structured_output: { schema: { type: 'object', properties: { severity: { type: 'string', enum: ['low', 'medium', 'high'] }, reason: { type: 'string' } }, required: ['severity', 'reason'] } }, output_key: 'classification', position: { x: 368, y: 280 } },
        { id: 'route',        type: 'condition',        label: 'Route by severity',             branches: [{ condition: { type: 'expr', expr: "$.state.classification.severity == 'high'" }, target: 'human_review' }], default_target: 'auto_respond', position: { x: 676, y: 280 } },
        { id: 'human_review', type: 'hitl_breakpoint',  label: 'Human review — high severity',  prompt: 'High-severity content requires your review.\n\nContent: {{$.state.content}}\nReason: {{$.state.classification.reason}}\n\nPlease provide your decision.', resume_schema: { type: 'object', properties: { decision: { type: 'string', enum: ['approve', 'reject', 'edit'] }, reviewer_note: { type: 'string' } }, required: ['decision'] }, output_key: 'reviewer_outcome', timeout_seconds: 86400, on_timeout: 'raise', position: { x: 984, y: 80 } },
        { id: 'auto_respond', type: 'llm_call',         label: 'Generate moderation response',  system_prompt: 'You are a content moderator. Write a clear, constructive moderation response.', prompt_template: 'Write a moderation response.\n\nContent: {{$.state.content}}\nSeverity: {{$.state.classification.severity}}', model_params: { temperature: 0.3, max_tokens: 300 }, output_key: 'response', position: { x: 984, y: 480 } },
        { id: 'done',         type: 'output',           label: 'Moderation result',             position: { x: 1292, y: 280 } },
      ],
      edges: [
        { type: 'direct', from: 'start',        to: 'classify' },
        { type: 'direct', from: 'classify',     to: 'route' },
        { type: 'direct', from: 'route',        to: 'human_review', label: 'high' },
        { type: 'direct', from: 'route',        to: 'auto_respond', label: 'low / medium' },
        { type: 'direct', from: 'human_review', to: 'done' },
        { type: 'direct', from: 'auto_respond', to: 'done' },
      ],
      flow_config: {
        checkpoint: { enabled: true, backend: 'postgres', connection_env: 'DATABASE_URL', namespace: 'moderation' },
        streaming:  { enabled: false },
        telemetry:  { enabled: true, provider: 'langfuse', project: 'content-moderation' },
      },
    },
  },
  {
    label: 'Parallel Risk Assessment',
    spec: {
      spec_version: '0.2.0',
      id: 'parallel-risk-assessment-flow',
      name: 'Parallel Multi-Agent Risk Assessment',
      description: 'Three specialist agents assess a document in parallel; results are merged into a unified risk report.',
      runtime_hints: { preferred_adapter: 'crewai', compatible: ['crewai', 'langgraph', 'mastra', 'microsoft_agent_framework'] },
      model_defaults: { model: 'gpt-4o' },
      state_schema: {
        type: 'object',
        properties: {
          document:       { type: 'string', description: 'Document text to assess' },
          legal_risk:     { type: 'object', description: 'Legal risk assessment output' },
          financial_risk: { type: 'object', description: 'Financial risk assessment output' },
          technical_risk: { type: 'object', description: 'Technical risk assessment output' },
          risk_report:    { type: 'string', description: 'Final synthesised risk report' },
        },
        required: ['document'],
      },
      agents: [
        { id: 'legal_analyst',     role: 'Legal Risk Analyst',     backstory: 'Experienced corporate lawyer.', goal: 'Identify legal risks and compliance gaps.', max_iter: 5 },
        { id: 'financial_analyst', role: 'Financial Risk Analyst', backstory: 'Senior financial analyst.', goal: 'Identify financial risks and adverse payment terms.', max_iter: 5 },
        { id: 'technical_analyst', role: 'Technical Risk Analyst', backstory: 'Engineering lead.', goal: 'Identify technical risks and unrealistic SLAs.', max_iter: 5 },
      ],
      nodes: [
        { id: 'start',            type: 'input',         label: 'Document input',                 output_schema: { type: 'object', properties: { document: { type: 'string' } } }, position: { x: 60,  y: 340 } },
        { id: 'fork',             type: 'parallel_fork', label: 'Dispatch to specialist agents',  targets: ['assess_legal', 'assess_financial', 'assess_technical'], position: { x: 368, y: 340 } },
        { id: 'assess_legal',     type: 'agent_role',    label: 'Legal risk assessment',          config: { agent_ref: 'legal_analyst', task_description: 'Analyse the document for legal risks:\n\n{{$.state.document}}', expected_output: 'JSON: risk_level, risks[], recommendations[]', output_field: 'legal_risk', memory_access: 'isolated', tool_approval: 'auto' }, position: { x: 676, y: 100 } },
        { id: 'assess_financial', type: 'agent_role',    label: 'Financial risk assessment',      config: { agent_ref: 'financial_analyst', task_description: 'Analyse the document for financial risks:\n\n{{$.state.document}}', expected_output: 'JSON: risk_level, risks[], recommendations[]', output_field: 'financial_risk', memory_access: 'isolated', tool_approval: 'auto' }, position: { x: 676, y: 340 } },
        { id: 'assess_technical', type: 'agent_role',    label: 'Technical risk assessment',      config: { agent_ref: 'technical_analyst', task_description: 'Analyse the document for technical risks:\n\n{{$.state.document}}', expected_output: 'JSON: risk_level, risks[], recommendations[]', output_field: 'technical_risk', memory_access: 'isolated', tool_approval: 'auto' }, position: { x: 676, y: 580 } },
        { id: 'join',             type: 'parallel_join', label: 'Collect all risk assessments',   wait_for: 'all', join_reducer: 'merge', output_key: 'risk_assessments', position: { x: 984, y: 340 } },
        { id: 'synthesise',       type: 'llm_call',      label: 'Synthesise risk report',         system_prompt: 'You are a risk committee chair. Synthesise three specialist risk assessments into a clear executive summary.', prompt_template: 'Synthesise into a unified executive risk report with overall risk level, cross-cutting themes, and top 5 prioritised recommendations.\n\nLegal: {{$.state.legal_risk}}\n\nFinancial: {{$.state.financial_risk}}\n\nTechnical: {{$.state.technical_risk}}', model_params: { temperature: 0.2, max_tokens: 1024 }, output_key: 'risk_report', position: { x: 1292, y: 340 } },
        { id: 'done',             type: 'output',        label: 'Risk report',                    position: { x: 1600, y: 340 } },
      ],
      edges: [
        { type: 'direct', from: 'start',            to: 'fork' },
        { type: 'direct', from: 'fork',             to: 'assess_legal' },
        { type: 'direct', from: 'fork',             to: 'assess_financial' },
        { type: 'direct', from: 'fork',             to: 'assess_technical' },
        { type: 'direct', from: 'assess_legal',     to: 'join' },
        { type: 'direct', from: 'assess_financial', to: 'join' },
        { type: 'direct', from: 'assess_technical', to: 'join' },
        { type: 'direct', from: 'join',             to: 'synthesise' },
        { type: 'direct', from: 'synthesise',       to: 'done' },
      ],
      flow_config: {
        checkpoint: { enabled: true, backend: 'sqlite' },
        streaming:  { enabled: true, mode: 'updates' },
        telemetry:  { enabled: true, provider: 'langfuse', project: 'risk-assessment' },
      },
    },
  },
  {
    label: 'Research Crew',
    spec: {
      spec_version: '0.2.0',
      id: 'research-crew-flow',
      name: 'Role-Based Research Crew',
      description: 'Researcher gathers findings, analyst interprets, writer produces the final report. context_from edges pass task context.',
      runtime_hints: { preferred_adapter: 'crewai', compatible: ['crewai', 'langgraph', 'mastra', 'microsoft_agent_framework'] },
      model_defaults: { model: 'gpt-4o' },
      state_schema: {
        type: 'object',
        properties: {
          topic:              { type: 'string', description: 'Research topic' },
          research_findings:  { type: 'string', description: 'Raw research findings' },
          analysis:           { type: 'string', description: 'Analyst interpretation' },
          report:             { type: 'string', description: 'Final written report' },
        },
        required: ['topic'],
      },
      agents: [
        { id: 'researcher', role: 'Senior Research Specialist', backstory: 'Expert at gathering accurate information.', goal: 'Find comprehensive, accurate information on the topic.', tools: ['web_search'], memory_config: { short_term: true, long_term: false, entity: false, user: false }, max_iter: 8 },
        { id: 'analyst',    role: 'Strategic Analyst', backstory: 'Turns raw research into sharp insights.', goal: 'Interpret findings and produce structured analysis.', max_iter: 5 },
        { id: 'writer',     role: 'Senior Technical Writer', backstory: 'Translates complex analysis into clear reports.', goal: 'Produce a polished, well-structured report.', allow_delegation: false, max_iter: 4 },
      ],
      memory_stores: {
        crew_shared: { type: 'hybrid', description: 'Shared store for the writer agent', backend: 'in_memory', scope: 'thread' },
      },
      tools: {
        web_search: { tool_ref: '@langchain/community/tools/TavilySearchResults', source: 'npm', description: 'Search the web for recent information' },
      },
      nodes: [
        { id: 'start',        type: 'input',      label: 'Research topic',        output_schema: { type: 'object', properties: { topic: { type: 'string' } } }, position: { x: 60,  y: 240 } },
        { id: 'research',     type: 'agent_role', label: 'Gather research findings', config: { agent_ref: 'researcher', task_description: 'Research the topic thoroughly using web search.\n\nTopic: {{$.state.topic}}', expected_output: 'At least 5 key findings with sources.', output_field: 'research_findings', memory_access: 'isolated', tool_approval: 'auto' }, position: { x: 368, y: 240 } },
        { id: 'analyse',      type: 'agent_role', label: 'Analyse findings',      config: { agent_ref: 'analyst', task_description: 'Analyse the research findings in context. Identify 3 key implications, gaps, and recommended direction.', expected_output: 'Key implications (3), knowledge gaps (1-3), recommended direction.', output_field: 'analysis', memory_access: 'isolated', tool_approval: 'auto' }, position: { x: 676, y: 240 } },
        { id: 'write_report', type: 'agent_role', label: 'Write final report',    config: { agent_ref: 'writer', task_description: 'Write a polished executive report on: {{$.state.topic}}.', expected_output: 'Executive summary (150 words), key findings, analysis (3 paragraphs), conclusion (100 words).', output_field: 'report', memory_access: 'shared', memory_store_id: 'crew_shared', tool_approval: 'human' }, position: { x: 984, y: 240 } },
        { id: 'done',         type: 'output',     label: 'Final report',          position: { x: 1292, y: 240 } },
      ],
      edges: [
        { type: 'direct', from: 'start',    to: 'research' },
        { type: 'direct', from: 'research', to: 'analyse',      context_from: ['research'] },
        { type: 'direct', from: 'analyse',  to: 'write_report', context_from: ['research', 'analyse'] },
        { type: 'direct', from: 'write_report', to: 'done' },
      ],
      flow_config: {
        process_type: 'sequential',
        checkpoint:   { enabled: true, backend: 'sqlite' },
        streaming:    { enabled: true, mode: 'updates' },
        telemetry:    { enabled: true, provider: 'langfuse', project: 'research-crew' },
      },
    },
  },
  {
    label: 'Debate Agent + A2A',
    spec: {
      spec_version: '0.2.0',
      id: 'debate-agent-a2a-flow',
      name: 'Debate Agent + A2A Exposure',
      description: 'Advocate prepares a position; advocate and devil\'s advocate debate under a judge. Exposed as an A2A agent.',
      runtime_hints: { preferred_adapter: 'microsoft_agent_framework', compatible: ['microsoft_agent_framework', 'langgraph', 'mastra'] },
      model_defaults: { model: 'gpt-4o' },
      state_schema: {
        type: 'object',
        properties: {
          proposition:      { type: 'string', description: 'The debate proposition' },
          advocate_position:{ type: 'string', description: "Advocate's prepared opening" },
          debate_transcript:{ type: 'string', description: 'Full debate transcript', reducer: 'append' },
          verdict:          { type: 'string', description: "Judge's final verdict" },
          summary:          { type: 'string', description: 'Structured output for A2A consumers' },
        },
        required: ['proposition'],
      },
      agents: [
        { id: 'advocate',       role: 'Debate Advocate',   backstory: 'Accomplished debater skilled at compelling arguments.', goal: 'Argue in favour of the proposition.', max_iter: 6 },
        { id: 'devil_advocate', role: "Devil's Advocate",  backstory: 'Critical thinker who challenges arguments rigorously.', goal: 'Challenge the proposition by exposing weaknesses.', max_iter: 6 },
        { id: 'judge',          role: 'Impartial Judge',   backstory: 'Fair adjudicator who evaluates arguments on merit.', goal: 'Monitor debate, intervene when circular, issue verdict ending with VERDICT.', max_iter: 3 },
      ],
      nodes: [
        { id: 'start',           type: 'input',        label: 'Debate proposition', output_schema: { type: 'object', properties: { proposition: { type: 'string' } } }, position: { x: 60, y: 260 } },
        { id: 'prepare_position',type: 'agent_role',   label: 'Advocate prepares opening', config: { agent_ref: 'advocate', task_description: 'Prepare a strong opening argument in favour of:\n\n{{$.state.proposition}}\n\nInclude: clear position, 3 supporting arguments with evidence, 1 anticipated counterargument.', expected_output: 'Structured opening argument (300-400 words).', output_field: 'advocate_position', memory_access: 'isolated', tool_approval: 'auto' }, position: { x: 368, y: 260 } },
        { id: 'debate',          type: 'agent_debate', label: 'Moderated debate', config: { agents: ['advocate', 'devil_advocate', 'judge'], max_rounds: 12, termination_condition: { type: 'expr', expr: "$.last_message contains 'VERDICT'" }, speaker_selection: 'round_robin', allow_repeat_speaker: false, output_field: 'debate_transcript' }, runtime_support: { microsoft_agent_framework: 'full', langgraph: 'partial', mastra: 'partial', crewai: 'partial' }, position: { x: 676, y: 260 } },
        { id: 'format_output',   type: 'transform',    label: 'Format A2A response', mode: 'mapping', mapping: [{ from: '$.state.proposition', to: '$.output.proposition' }, { from: '$.state.debate_transcript', to: '$.output.transcript' }, { from: '$.state.verdict', to: '$.output.verdict' }], position: { x: 984, y: 260 } },
        { id: 'done',            type: 'output',       label: 'Debate result', position: { x: 1292, y: 260 } },
      ],
      edges: [
        { type: 'direct', from: 'start',            to: 'prepare_position' },
        { type: 'direct', from: 'prepare_position', to: 'debate',         context_from: ['prepare_position'] },
        { type: 'direct', from: 'debate',           to: 'format_output' },
        { type: 'direct', from: 'format_output',    to: 'done' },
      ],
      flow_config: {
        process_type: 'consensual',
        checkpoint:   { enabled: true, backend: 'postgres', connection_env: 'DATABASE_URL' },
        streaming:    { enabled: true, mode: 'tokens' },
        telemetry:    { enabled: true, provider: 'azure_monitor', project: 'debate-agent' },
        a2a_config:   {
          enabled: true,
          agent_name: 'Debate Agent',
          agent_description: 'Given a proposition, orchestrates a structured debate returning a verdict and full transcript.',
          version: '1.0.0',
          capabilities: ['streaming', 'stateTransitionHistory'],
          authentication: 'api_key',
          input_schema_ref: 'start',
          output_schema_ref: 'done',
          skills: [{ id: 'structured-debate', name: 'Structured Debate', description: 'Runs a moderated multi-round debate and returns a verdict.' }],
        },
      },
    },
  },
]
