"""
itsharness — CrewAI adapter  v0.2.0
Generates runnable CrewAI Python code from a FlowSpec JSON.

Coverage:
  ✓ agents[]            → crewai.Agent instances
  ✓ agent_role          → crewai.Task with agent binding + expected_output
  ✓ llm_call            → Task with prompt_template as description
  ✓ tool_invoke         → Task with tool binding
  ✓ transform           → Task with mapping description
  ✓ hitl_breakpoint     → Task(human_input=True)
  ✓ memory_read         → Task with retrieval description
  ✓ memory_write        → Task with write description (ADR-001 RFC-2 resolved)
  ✓ parallel_fork       → downstream Tasks gain async_execution=True
  ✓ parallel_join       → aggregation Task
  ✓ condition           → synthesised branch-decision Task + warning
  ✓ agent_debate        → inner Crew stub + warning
  ✓ subgraph            → nested Crew stub + warning
  ✓ process_type        → Crew(process=Process.sequential/hierarchical)
  ✓ flow_config.checkpoint → Crew(memory=True)
  ✓ context_from        → Task.context=[...] (ADR-001 RFC-1 resolved)
  ✓ memory_write.tier   → XXXMemory() in Crew constructor (ADR-001 RFC-2 resolved)
"""

from __future__ import annotations
import textwrap
from collections import defaultdict, deque
from typing import Any

ADAPTER_VERSION = "0.2.0"
CREWAI_MIN      = ">=0.80.0"

# ADR-001 RFC-2: memory_write.tier → CrewAI memory class map
_TIER_CLASS: dict[str, str] = {
    "short":  "ShortTermMemory",
    "long":   "LongTermMemory",
    "entity": "EntityMemory",
    "user":   "UserMemory",
}


# ─── Utilities ────────────────────────────────────────────────────────────────

def py_str(s: str) -> str:
    """Single-line Python string literal with minimal escaping."""
    return '"""' + s.replace('\\', '\\\\').replace('"""', '\\"\\"\\"') + '"""'


def safe_id(s: str) -> str:
    """Convert any node/agent ID to a valid Python identifier."""
    return "".join(c if (c.isalnum() or c == "_") else "_" for c in s).lstrip("0123456789") or "_node"


def dedent0(text: str) -> str:
    return textwrap.dedent(text).lstrip("\n")


# ─── Topological sort (Kahn's algorithm) ─────────────────────────────────────

def topo_sort(nodes: list[dict], edges: list[dict]) -> list[dict]:
    id_to_node: dict[str, dict] = {n["id"]: n for n in nodes}
    in_deg: dict[str, int]       = {n["id"]: 0 for n in nodes}
    adj: dict[str, list[str]]    = defaultdict(list)

    for e in edges:
        src = e.get("from", e.get("source", ""))
        tgt = e.get("to",   e.get("target", ""))
        if src in id_to_node and tgt in id_to_node:
            adj[src].append(tgt)
            in_deg[tgt] += 1

    q: deque[str] = deque(nid for nid, d in in_deg.items() if d == 0)
    order: list[str] = []
    while q:
        nid = q.popleft()
        order.append(nid)
        for tgt in adj[nid]:
            in_deg[tgt] -= 1
            if in_deg[tgt] == 0:
                q.append(tgt)

    seen = set(order)
    for n in nodes:  # append any remaining (cycles / disconnected)
        if n["id"] not in seen:
            order.append(n["id"])

    return [id_to_node[nid] for nid in order if nid in id_to_node]


def find_parallel_targets(spec: dict) -> set[str]:
    """IDs of nodes that are direct targets of a parallel_fork."""
    fork_ids = {n["id"] for n in spec.get("nodes", []) if n["type"] == "parallel_fork"}
    out: set[str] = set()
    for e in spec.get("edges", []):
        src = e.get("from", e.get("source", ""))
        tgt = e.get("to",   e.get("target", ""))
        if src in fork_ids:
            out.add(tgt)
    return out


def build_context_map(edges: list[dict]) -> dict[str, list[str]]:
    """node_id → list of context_from node IDs arriving on that node's incoming edges."""
    ctx: dict[str, list[str]] = defaultdict(list)
    for e in edges:
        cf  = e.get("context_from", [])
        tgt = e.get("to", e.get("target", ""))
        if cf and tgt:
            ctx[tgt].extend(cf)
    return ctx


# ─── Section generators ───────────────────────────────────────────────────────

def gen_header(spec: dict) -> str:
    name   = spec.get("name", spec.get("id", "unknown"))
    fid    = spec.get("id",   "unknown")
    nc, ec = len(spec.get("nodes", [])), len(spec.get("edges", []))
    return dedent0(f"""\
        \"\"\"
        CrewAI code generated by itsharness-adapter v{ADAPTER_VERSION}
        Flow   : {name}  ({fid})
        Nodes  : {nc}  |  Edges: {ec}
        Requires: crewai{CREWAI_MIN}
        \"\"\"

        from crewai import Agent, Task, Crew, Process
        from crewai.memory import ShortTermMemory, LongTermMemory, EntityMemory, UserMemory
        from crewai.tools import BaseTool
        import os
    """)


def gen_tools(spec: dict) -> str:
    tools = spec.get("tools", {})
    if not tools:
        return "# (no tools defined)\n"

    lines: list[str] = [
        "# ─── Tools ──────────────────────────────────────────────────────────────────",
        "# Stub classes — replace _run with real implementations.",
        "",
    ]
    for tid, tdef in tools.items():
        vid  = safe_id(tid)
        desc = tdef.get("description", tid)
        ref  = tdef.get("tool_ref", tid)
        lines += [
            f"# tool_ref: {ref}",
            f"class _{vid.capitalize()}Tool(BaseTool):",
            f"    name: str = {repr(tid)}",
            f"    description: str = {repr(desc)}",
            f"    def _run(self, query: str) -> str:",
            f"        raise NotImplementedError({repr(f'Implement {tid}')})",
            "",
            f"{vid} = _{vid.capitalize()}Tool()",
            "",
        ]
    return "\n".join(lines)


def gen_agents(spec: dict) -> str:
    agents = spec.get("agents", [])
    tool_ids = set(spec.get("tools", {}).keys())

    lines: list[str] = [
        "# ─── Agents ─────────────────────────────────────────────────────────────────",
        "",
    ]

    for a in agents:
        vid      = safe_id(a["id"])
        role     = a.get("role", a["id"])
        backstory = a.get("backstory", "")
        goal     = a.get("goal", "")
        model    = a.get("model", "")
        a_tools  = [t for t in a.get("tools", []) if t in tool_ids]
        mem_cfg  = a.get("memory_config", {})
        use_mem  = any(mem_cfg.values()) if mem_cfg else False
        max_iter = a.get("max_iter", 10)
        allow_d  = a.get("allow_delegation", False)

        lines.append(f"{vid} = Agent(")
        lines.append(f"    role={repr(role)},")
        lines.append(f"    backstory={repr(backstory)},")
        lines.append(f"    goal={repr(goal)},")
        if model:
            lines.append(f"    llm={repr(model)},")
        if a_tools:
            lines.append(f"    tools=[{', '.join(safe_id(t) for t in a_tools)}],")
        if use_mem:
            lines.append(f"    memory=True,")
        lines.append(f"    max_iter={max_iter},")
        lines.append(f"    allow_delegation={allow_d},")
        lines.append(f"    verbose=True,")
        lines.append(f")")
        lines.append("")

    lines += [
        "# Generic executor for non-agent nodes (llm_call, tool_invoke, transform, etc.)",
        "_executor = Agent(",
        '    role="Executor",',
        '    backstory="A general-purpose executor that runs non-agent workflow steps.",',
        '    goal="Complete the assigned step accurately and concisely.",',
        "    verbose=True,",
        ")",
        "",
    ]
    return "\n".join(lines)


def gen_tasks(spec: dict, sorted_nodes: list[dict], warnings: list[str]) -> str:
    agents_by_id   = {a["id"]: a for a in spec.get("agents", [])}
    parallel_tgts  = find_parallel_targets(spec)
    ctx_map        = build_context_map(spec.get("edges", []))

    lines: list[str] = [
        "# ─── Tasks ──────────────────────────────────────────────────────────────────",
        "# Ordered by execution sequence (topological sort of spec edges).",
        "",
    ]

    for node in sorted_nodes:
        ntype = node["type"]
        nid   = node["id"]
        vid   = safe_id(nid)
        ctx   = ctx_map.get(nid, [])
        is_parallel = nid in parallel_tgts

        if ntype in ("input", "output", "annotation"):
            lines.append(f"# '{nid}' ({ntype}) — no Task needed")
            continue

        if ntype == "parallel_fork":
            tgts = node.get("targets", [])
            lines.append(f"# parallel_fork '{nid}' — downstream tasks have async_execution=True")
            lines.append(f"# targets: {tgts}")
            lines.append("")
            continue

        # ── Build task kwargs shared across types ────────────────────────────
        def emit_task(description: str, expected_output: str, agent_var: str,
                      extra_lines: list[str] | None = None) -> None:
            lines.append(f"task_{vid} = Task(")
            lines.append(f"    description={repr(description)},")
            lines.append(f"    expected_output={repr(expected_output)},")
            lines.append(f"    agent={agent_var},")
            if is_parallel:
                lines.append(f"    async_execution=True,  # parallel_fork branch")
            if extra_lines:
                lines.extend(f"    {l}" for l in extra_lines)
            # ADR-001 RFC-1: context_from → Task.context=[task_a, task_b]
            if ctx:
                ctx_vars = ", ".join(f"task_{safe_id(c)}" for c in ctx)
                lines.append(f"    context=[{ctx_vars}],")
            lines.append(")")
            lines.append("")

        # ── agent_role ───────────────────────────────────────────────────────
        if ntype == "agent_role":
            cfg       = node.get("config", {})
            agent_ref = cfg.get("agent_ref", "")
            agent_var = safe_id(agent_ref) if agent_ref in agents_by_id else "_executor"
            if agent_ref and agent_ref not in agents_by_id:
                warnings.append(f"agent_role '{nid}': agent_ref '{agent_ref}' not in agents[]")

            task_desc = cfg.get("task_description", "Execute agent task.")
            expected  = cfg.get("expected_output", "Task result.")
            out_field = cfg.get("output_field", "")
            human_inp = cfg.get("tool_approval", "auto") == "human"

            extra = []
            if out_field:
                extra.append(f"# output_field={repr(out_field)} — capture via callback or post-process")
            if human_inp:
                extra.append("human_input=True,  # tool_approval=human")
            emit_task(task_desc, expected, agent_var, extra)
            continue

        # ── agent_debate ─────────────────────────────────────────────────────
        if ntype == "agent_debate":
            cfg        = node.get("config", {})
            a_refs     = cfg.get("agents", [])
            max_rounds = cfg.get("max_rounds", 10)
            out_field  = cfg.get("output_field", "")
            a_vars     = " + ".join(f"[{safe_id(a)}]" for a in a_refs if a in agents_by_id)
            lines += [
                f"# agent_debate '{nid}' — synthesised as an inner sequential Crew",
                f"# (CrewAI has no native GroupChat; production should use a loop)",
                f"_debate_crew_{vid} = Crew(",
                f"    agents={a_vars or '[]'},",
                f"    tasks=[],  # populate debate turn tasks at runtime",
                f"    process=Process.sequential,",
                f"    verbose=True,",
                f"    # max_rounds={max_rounds}",
                f")",
            ]
            emit_task(
                f"Orchestrate a {max_rounds}-round debate between agents {a_refs}.",
                f"Debate transcript and verdict.{' Stored in state.' + out_field if out_field else ''}",
                "_executor",
                [f"# invoke _debate_crew_{vid}.kickoff() inside the agent callback"],
            )
            warnings.append(
                f"agent_debate '{nid}': synthesised as sequential inner Crew — "
                f"implement round loop or use MS Agent Framework for native GroupChat"
            )
            continue

        # ── hitl_breakpoint ──────────────────────────────────────────────────
        if ntype == "hitl_breakpoint":
            prompt    = node.get("prompt", "Please review and provide input.")
            timeout_s = node.get("timeout_seconds", 86400)
            out_key   = node.get("output_key", "")
            emit_task(
                prompt,
                f"Human reviewer decision.{' Stored in state.' + out_key if out_key else ''}",
                "_executor",
                [
                    "human_input=True,  # hitl_breakpoint",
                    f"# timeout_seconds={timeout_s} — enforce at orchestration layer",
                ],
            )
            continue

        # ── llm_call ─────────────────────────────────────────────────────────
        if ntype == "llm_call":
            sys_p       = node.get("system_prompt", "")
            prompt      = node.get("prompt_template", "")
            out_key     = node.get("output_key", "")
            fail_branch = node.get("fail_branch") or {}
            desc = "\n\n".join(filter(None, [sys_p, prompt])) or "Call LLM with configured prompt."
            extra: list[str] = []
            if fail_branch.get("target"):
                retry = fail_branch.get("retry") or {}
                max_a = retry.get("max_attempts", 3)
                extra.append(f"# fail_branch → target={repr(fail_branch['target'])}, max_attempts={max_a}")
                extra.append(f"# Use Task(max_retries={max_a}) or wrap crew.kickoff() in a try/except")
                warnings.append(f"llm_call '{nid}': fail_branch.target='{fail_branch['target']}' noted above")
            emit_task(
                desc,
                f"LLM-generated text.{' Stored in state.' + out_key if out_key else ''}",
                "_executor",
                extra or None,
            )
            continue

        # ── tool_invoke ──────────────────────────────────────────────────────
        if ntype == "tool_invoke":
            tool_id     = node.get("tool_id", "")
            tool_ref    = f"[{safe_id(tool_id)}]" if tool_id else "[]"
            fail_branch = node.get("fail_branch") or {}
            extra = [f"tools={tool_ref},"]
            if fail_branch.get("target"):
                retry = fail_branch.get("retry") or {}
                max_a = retry.get("max_attempts", 3)
                extra.append(f"# fail_branch → target={repr(fail_branch['target'])}, max_attempts={max_a}")
                warnings.append(f"tool_invoke '{nid}': fail_branch.target='{fail_branch['target']}' noted above")
            emit_task(
                f"Invoke tool '{tool_id}' with the current state inputs.",
                "Tool invocation result.",
                "_executor",
                extra,
            )
            continue

        # ── memory_read ──────────────────────────────────────────────────────
        if ntype == "memory_read":
            store_id = node.get("store_id", "")
            mode     = node.get("retrieval_mode", "key_value")
            out_key  = node.get("output_key", "")
            emit_task(
                f"Read from memory store '{store_id}' using {mode} retrieval.",
                f"Retrieved content.{' Stored in state.' + out_key if out_key else ''}",
                "_executor",
                [f"# CrewAI uses built-in agent memory — configure via Agent(memory=True)"],
            )
            continue

        # ── memory_write ─────────────────────────────────────────────────────
        if ntype == "memory_write":
            store_id = node.get("store_id", "")
            key_expr = node.get("key_expr", "")
            val_expr = node.get("value_expr", "")
            tier     = node.get("tier", "short")
            emit_task(
                f"Write to memory store '{store_id}': key={key_expr}, value={val_expr}.",
                "Memory write confirmed.",
                "_executor",
                [f"# memory tier: '{tier}' → {_TIER_CLASS.get(tier, 'ShortTermMemory')} configured at Crew level (ADR-001 RFC-2)"],
            )
            continue

        # ── transform ────────────────────────────────────────────────────────
        if ntype == "transform":
            mode    = node.get("mode", "mapping")
            fn_ref  = node.get("fn_ref", "")
            mapping = node.get("mapping", [])
            if mode == "fn_ref" and fn_ref:
                desc = f"Transform state using function ref '{fn_ref}'."
            elif mapping:
                pairs = "; ".join(
                    f"{m.get('from','')}→{m.get('to','')}" for m in mapping[:4]
                )
                desc = f"Map state fields: {pairs}."
            else:
                desc = "Transform the current state."
            emit_task(desc, "Transformed state fields populated.", "_executor")
            continue

        # ── condition ────────────────────────────────────────────────────────
        if ntype == "condition":
            branches    = node.get("branches", [])
            def_target  = node.get("default_target", "")
            branch_list = [b.get("target", "") for b in branches] + (
                [f"{def_target} (default)"] if def_target else []
            )
            emit_task(
                "Evaluate conditions and return the name of the branch to follow.",
                f"One of: {', '.join(filter(None, branch_list))}.",
                "_executor",
            )
            warnings.append(
                f"condition '{nid}': CrewAI has no native routing — inspect "
                f"task_{vid}.output after kickoff to branch manually"
            )
            continue

        # ── parallel_join ────────────────────────────────────────────────────
        if ntype == "parallel_join":
            wait_for = node.get("wait_for", "all")
            reducer  = node.get("join_reducer", "merge")
            emit_task(
                f"Collect and merge parallel branch results (wait_for={wait_for}, reducer={reducer}).",
                "Merged state from all parallel branches.",
                "_executor",
            )
            continue

        # ── subgraph ─────────────────────────────────────────────────────────
        if ntype == "subgraph":
            flow_ref = node.get("flow_ref", "")
            emit_task(
                f"Execute subgraph '{flow_ref}' with the current state inputs.",
                "Subgraph execution result.",
                "_executor",
                [f"# Load and kickoff a nested Crew for flow_ref='{flow_ref}'"],
            )
            warnings.append(
                f"subgraph '{nid}': flow_ref='{flow_ref}' — compile and invoke "
                f"as a nested Crew.kickoff() call"
            )
            continue

        # ── fallback ─────────────────────────────────────────────────────────
        warnings.append(f"Unknown node type '{ntype}' for '{nid}' — stub task emitted")
        emit_task(
            f"Execute {ntype} node '{nid}'.",
            "Result.",
            "_executor",
        )

    return "\n".join(lines)


def gen_crew_and_kickoff(spec: dict, sorted_nodes: list[dict]) -> str:
    agents_by_id = {a["id"]: a for a in spec.get("agents", [])}
    flow_config  = spec.get("flow_config", {})
    process_type = flow_config.get("process_type", "sequential")
    manager_ref  = flow_config.get("manager_agent_ref", "")
    checkpoint   = flow_config.get("checkpoint", {})
    telemetry    = flow_config.get("telemetry", {})

    process_map = {
        "sequential":   "Process.sequential",
        "hierarchical": "Process.hierarchical",
        "consensual":   "Process.sequential",   # no direct equivalent
    }
    process_val = process_map.get(process_type, "Process.sequential")

    # Collect task vars (skip input/output/annotation/parallel_fork — they have no task_*)
    skip_types = {"input", "output", "annotation", "parallel_fork"}
    task_vars  = [
        f"task_{safe_id(n['id'])}"
        for n in sorted_nodes
        if n["type"] not in skip_types
    ]
    agent_vars = [safe_id(a["id"]) for a in spec.get("agents", [])] + ["_executor"]

    lines: list[str] = [
        "",
        "# ─── Crew ───────────────────────────────────────────────────────────────────",
        "",
        "crew = Crew(",
        f"    agents=[{', '.join(agent_vars)}],",
        f"    tasks=[{', '.join(task_vars)}],",
        f"    process={process_val},",
    ]
    if process_type == "hierarchical" and manager_ref in agents_by_id:
        lines.append(f"    manager_agent={safe_id(manager_ref)},")
    if process_type == "consensual":
        lines.append(f"    # process_type=consensual → no direct equivalent; using sequential")
    if checkpoint.get("enabled"):
        backend = checkpoint.get("backend", "memory")
        lines.append(f"    memory=True,  # checkpoint.backend={backend}")

    # ADR-001 RFC-2: add XXXMemory() instances for each tier used by memory_write nodes
    used_tiers = {
        n.get("tier", "short")
        for n in spec.get("nodes", [])
        if n["type"] == "memory_write"
    }
    for tier in sorted(used_tiers):
        cls = _TIER_CLASS.get(tier)
        if cls:
            lines.append(f"    {tier}_term_memory={cls}(),  # from memory_write tier='{tier}' (ADR-001)")

    if telemetry.get("enabled"):
        provider = telemetry.get("provider", "")
        lines.append(f"    # telemetry.provider={provider} — configure via env vars")
    lines += ["    verbose=True,", ")", ""]

    # Derive example kickoff inputs from state_schema.required
    state_schema   = spec.get("state_schema", {})
    required_flds  = state_schema.get("required", [])
    props          = state_schema.get("properties", {})
    example_inputs = {
        f: f"<{props.get(f, {}).get('type', 'str')}>"
        for f in required_flds
    }

    lines += [
        "",
        "# ─── Kickoff ─────────────────────────────────────────────────────────────────",
        "",
        "if __name__ == '__main__':",
        f"    result = crew.kickoff(",
        f"        inputs={repr(example_inputs) if example_inputs else '{}'},",
        f"    )",
        f"    print(result)",
    ]
    return "\n".join(lines)


# ─── Public API ───────────────────────────────────────────────────────────────

def compile_crewai(spec: dict) -> tuple[str, list[str]]:
    """
    Compile a FlowSpec dict to CrewAI Python source code.
    Returns (code: str, warnings: list[str]).
    """
    warnings: list[str] = []
    nodes = spec.get("nodes", [])
    edges = spec.get("edges", [])

    if not nodes:
        return "# Empty spec — no nodes to compile.\n", []

    sorted_nodes = topo_sort(nodes, edges)

    code = "\n\n".join(filter(None, [
        gen_header(spec),
        gen_tools(spec),
        gen_agents(spec),
        gen_tasks(spec, sorted_nodes, warnings),
        gen_crew_and_kickoff(spec, sorted_nodes),
    ]))
    return code, warnings
