"""
itsharness — LangGraph adapter (stub)
Phase 1: returns empty code. Real codegen after RFC closes.
"""

import json
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="itsharness-adapter", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://canvas:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class CompileRequest(BaseModel):
    spec: dict


class CompileResponse(BaseModel):
    runtime:  str
    code:     str
    warnings: list[str]


@app.get("/health")
def health():
    return {"status": "ok", "adapter": "langgraph", "phase": "1-stub"}


@app.post("/compile", response_model=CompileResponse)
def compile_flow(req: CompileRequest) -> CompileResponse:
    """
    Reads a FlowSpec JSON and emits LangGraph Python code.
    
    Phase 1 stub: validates the spec is present and returns a placeholder.
    Real codegen is gated on RFC close — field names (output_key, query_expr,
    context_from semantics) are the open questions most likely to change.
    """
    spec = req.spec

    if "nodes" not in spec:
        raise HTTPException(status_code=400, detail="spec.nodes is required")

    node_ids = [n["id"] for n in spec["nodes"]]
    edge_count = len(spec.get("edges", []))

    warnings: list[str] = []
    
    # Warn on node types not yet supported in this adapter version
    unsupported = {"agent_role", "agent_debate"}
    for node in spec["nodes"]:
        if node["type"] in unsupported:
            warnings.append(
                f"Node '{node['id']}' (type={node['type']}) synthesis not yet implemented — "
                f"codegen for this type is scheduled for Phase 1 completion after RFC."
            )

    stub_code = f'''\
"""
LangGraph code generated by itsharness-adapter v0.1.0-stub
Flow: {spec.get("name", spec.get("id", "unknown"))}
Nodes: {len(node_ids)} | Edges: {edge_count}

NOTE: This is a Phase 1 stub. Real codegen will be implemented
after the RFC comment period closes and spec field names are locked.
"""

from langgraph.graph import StateGraph, START, END
from typing import TypedDict

# --- State ---
class FlowState(TypedDict):
    pass  # TODO: generate from spec.state_schema

# --- Graph ---
graph = StateGraph(FlowState)

# TODO: nodes -> graph.add_node()
# TODO: edges -> graph.add_edge() / graph.add_conditional_edges()

compiled = graph.compile()
'''

    return CompileResponse(runtime="langgraph", code=stub_code, warnings=warnings)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)
