"""
DO NOT EDIT — generated from spec/memory-core.json by spec/gen-memory-core.mjs.
Run `node spec/gen-memory-core.mjs` after editing the source. CI fails if this file is stale.
Agent memory framework plan, phase M8 (shared contract).
"""

from __future__ import annotations

from typing import Any

MEMORY_CORE_VERSION: str = "1.0.0"

DEFAULT_MEMORY_BUDGET_CHARS: int = 4000

BUDGET_HEADER: str = "\nKnown facts about the user:\n"

BUDGET_LINE_FORMAT: str = "- {text}{suffix}"

UNCONFIRMED_SUFFIX: str = " (unconfirmed)"

BUDGET_SEPARATOR_COST: int = 1

TIER_PRIORITY: dict[str, int] = {
    "identity": 0,
    "preference": 0,
    "semantic": 1,
    "episodic": 2,
}

SESSION_PRIORITY: int = 2

LEGACY_FACT_CAP: dict[str, Any] = {
    "value": 20,
    "ported": False,
}

FACT_ID_FORMAT: str = "{text}|{extractedAt}"

AUDIT_LOG_KEEP: int = 500

STORE_KEYS: dict[str, str] = {
    "durable": "facts:durable",
    "pending": "facts:pending-confirmation",
    "rejected": "facts:rejected",
    "retired": "facts:retired",
    "audit": "memory:audit",
    "consolidation_state": "memory:consolidation-state",
    "off": "memory:off",
    "session_facts_prefix": "facts:",
    "archive": "facts:archive",
    "proposals": "memory:proposals",
    "episodic_prefix": "episodic:",
}

FACT_FIELDS: list[dict[str, Any]] = [
    {
        "name": "text",
        "type": "string",
        "required": True,
        "phase": "M0",
        "port": "yes",
    },
    {
        "name": "extractedAt",
        "type": "string",
        "required": True,
        "phase": "M0",
        "port": "yes",
    },
    {
        "name": "sourceTurn",
        "type": "string",
        "required": True,
        "phase": "M0",
        "port": "yes",
    },
    {
        "name": "durable",
        "type": "boolean",
        "required": True,
        "phase": "M0",
        "port": "yes",
    },
    {
        "name": "source",
        "type": "FactSource",
        "required": True,
        "phase": "M0",
        "port": "yes",
    },
    {
        "name": "confidence",
        "type": "FactConfidence",
        "required": False,
        "phase": "M0",
        "port": "yes",
    },
    {
        "name": "category",
        "type": "FactCategory",
        "required": False,
        "phase": "M0",
        "port": "yes",
    },
    {
        "name": "project",
        "type": "string",
        "required": False,
        "phase": "M0",
        "port": "yes",
    },
    {
        "name": "key",
        "type": "string",
        "required": False,
        "phase": "M1",
        "port": "yes",
    },
    {
        "name": "supersedes",
        "type": "string",
        "required": False,
        "phase": "M1",
        "port": "yes",
    },
    {
        "name": "retiredAt",
        "type": "string",
        "required": False,
        "phase": "M1",
        "port": "yes",
    },
    {
        "name": "injectedCount",
        "type": "number",
        "required": False,
        "phase": "M1",
        "port": "yes",
    },
    {
        "name": "lastInjectedAt",
        "type": "string",
        "required": False,
        "phase": "M1",
        "port": "yes",
    },
    {
        "name": "origin",
        "type": "FactOrigin",
        "required": False,
        "phase": "M2",
        "port": "yes",
    },
    {
        "name": "evidence",
        "type": "string",
        "required": False,
        "phase": "M2",
        "port": "yes",
    },
    {
        "name": "flagged",
        "type": "boolean",
        "required": False,
        "phase": "M2",
        "port": "yes",
    },
]

FACT_TRANSIENT_FIELDS: list[str] = [
    "judgement",
]

PENDING_FACT_EXTRA_FIELDS: list[dict[str, Any]] = [
    {
        "name": "previouslyRejected",
        "type": "boolean",
        "required": False,
        "port": "deferred",
    },
    {
        "name": "proposedOp",
        "type": "'retire'",
        "required": False,
        "port": "deferred",
    },
    {
        "name": "retireTargetId",
        "type": "string",
        "required": False,
        "port": "deferred",
    },
]

PENDING_FACT_DEFAULT_CATEGORY: str = "other"

FACT_SOURCES: list[str] = [
    "user_asserted",
    "model_inferred",
    "observed",
    "externally_verified",
]

FACT_ORIGINS: list[str] = [
    "user",
    "agent",
    "tool",
    "web",
]

DEFAULT_FACT_ORIGIN: str = "user"

FACT_CONFIDENCES: list[str] = [
    "high",
    "medium",
    "low",
]

FACT_CATEGORIES: list[str] = [
    "identity",
    "health",
    "preference",
    "location",
    "occupation",
    "relationships",
    "project",
    "other",
]

MEMORY_TIERS: list[str] = [
    "episodic",
    "semantic",
    "procedural",
    "preference",
    "commitment",
    "identity",
]

TIER_RULES: dict[str, dict[str, Any]] = {
    "episodic": {
        "allowed_sources": [
            "user_asserted",
            "model_inferred",
            "observed",
            "externally_verified",
        ],
        "retention": "session",
        "contradiction_checked": False,
    },
    "semantic": {
        "allowed_sources": [
            "user_asserted",
            "model_inferred",
            "externally_verified",
        ],
        "retention": "durable",
        "contradiction_checked": True,
    },
    "identity": {
        "allowed_sources": [
            "user_asserted",
            "model_inferred",
        ],
        "retention": "durable",
        "contradiction_checked": True,
    },
    "preference": {
        "allowed_sources": [
            "user_asserted",
            "model_inferred",
        ],
        "retention": "durable",
        "contradiction_checked": True,
    },
    "procedural": {
        "allowed_sources": [],
        "retention": "durable",
        "contradiction_checked": False,
    },
    "commitment": {
        "allowed_sources": [],
        "retention": "durable",
        "contradiction_checked": False,
    },
}

TIER_RULE_ORDER: list[dict[str, Any]] = [
    {
        "id": "non_user_origin",
        "tier": "episodic",
        "when": {
            "all": [
                {
                    "field": "origin",
                    "present": True,
                },
                {
                    "field": "origin",
                    "neq": "user",
                },
            ],
        },
    },
    {
        "id": "observed",
        "tier": "episodic",
        "when": {
            "field": "source",
            "eq": "observed",
        },
    },
    {
        "id": "model_inferred_unconfirmed",
        "tier": "episodic",
        "when": {
            "all": [
                {
                    "field": "source",
                    "eq": "model_inferred",
                },
                {
                    "not": {
                        "all": [
                            {
                                "field": "durable",
                                "eq": True,
                            },
                            {
                                "field": "confidence",
                                "eq": "high",
                            },
                        ],
                    },
                },
            ],
        },
    },
    {
        "id": "durable_identity",
        "tier": "identity",
        "when": {
            "all": [
                {
                    "field": "durable",
                    "eq": True,
                },
                {
                    "field": "category",
                    "eq": "identity",
                },
            ],
        },
    },
    {
        "id": "durable_preference",
        "tier": "preference",
        "when": {
            "all": [
                {
                    "field": "durable",
                    "eq": True,
                },
                {
                    "field": "category",
                    "eq": "preference",
                },
            ],
        },
    },
    {
        "id": "default",
        "tier": "semantic",
        "when": {
            "always": True,
        },
    },
]

WRITE_MODES: list[str] = [
    "auto",
    "staged",
    "user_only",
]

DEFAULT_WRITE_MODE: str = "staged"

WRITERS: list[str] = [
    "in_turn",
    "digest",
    "reviewer",
    "consolidation",
]

WRITE_ROUTES: list[str] = [
    "durable",
    "pending",
    "session",
]

WRITE_ROUTE_TABLE: list[dict[str, Any]] = [
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "high",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "high",
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "high",
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "medium",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "medium",
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "medium",
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "low",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "low",
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "low",
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": None,
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": None,
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": None,
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "high",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "high",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "high",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "medium",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "medium",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "medium",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": None,
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": None,
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": None,
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "high",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "high",
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "high",
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "medium",
        "mode": "auto",
        "route": "pending",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "medium",
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "medium",
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": None,
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": None,
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": None,
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "high",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "high",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "high",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "medium",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "medium",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "medium",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": None,
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": None,
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": None,
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": "high",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": "high",
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": "high",
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": "medium",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": "medium",
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": "medium",
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": "low",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": "low",
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": "low",
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": None,
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": None,
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": True,
        "confidence": None,
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": "high",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": "high",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": "high",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": "medium",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": "medium",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": "medium",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": None,
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": None,
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "observed",
        "durable": False,
        "confidence": None,
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "high",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "high",
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "high",
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "medium",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "medium",
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "medium",
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "low",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "low",
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "low",
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": None,
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": None,
        "mode": "staged",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": None,
        "mode": "user_only",
        "route": "durable",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "high",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "high",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "high",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "medium",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "medium",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "medium",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": None,
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": None,
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "in_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": None,
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "high",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "high",
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "high",
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "medium",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "medium",
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "medium",
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": None,
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": None,
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": True,
        "confidence": None,
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "high",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "high",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "high",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "medium",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "medium",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "medium",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": None,
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": None,
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "user_asserted",
        "durable": False,
        "confidence": None,
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "high",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "high",
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "high",
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "medium",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "medium",
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "medium",
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": None,
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": None,
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": True,
        "confidence": None,
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "high",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "high",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "high",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "medium",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "medium",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "medium",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": None,
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": None,
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "model_inferred",
        "durable": False,
        "confidence": None,
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": "high",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": "high",
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": "high",
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": "medium",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": "medium",
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": "medium",
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": None,
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": None,
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": True,
        "confidence": None,
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": "high",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": "high",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": "high",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": "medium",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": "medium",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": "medium",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": None,
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": None,
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "observed",
        "durable": False,
        "confidence": None,
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "high",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "high",
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "high",
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "medium",
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "medium",
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "medium",
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": None,
        "mode": "auto",
        "route": "durable",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": None,
        "mode": "staged",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": True,
        "confidence": None,
        "mode": "user_only",
        "route": "pending",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "high",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "high",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "high",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "medium",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "medium",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "medium",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "low",
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "low",
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": "low",
        "mode": "user_only",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": None,
        "mode": "auto",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": None,
        "mode": "staged",
        "route": "session",
    },
    {
        "writer_class": "cross_turn",
        "source": "externally_verified",
        "durable": False,
        "confidence": None,
        "mode": "user_only",
        "route": "session",
    },
]

ADMIT_ACTIONS: list[str] = [
    "admit",
    "session",
    "flag",
    "drop",
]

GATE_RULES: list[dict[str, Any]] = [
    {
        "id": "gate_off",
        "when": {
            "gate_on": False,
        },
        "action": "admit",
        "terminal": True,
        "effects": {
            "apply_default_origin": False,
        },
    },
    {
        "id": "not_judged",
        "when": {
            "judged": False,
        },
        "action": "admit",
        "terminal": True,
        "effects": {},
    },
    {
        "id": "missing_judgement",
        "when": {
            "judgement_complete": False,
        },
        "action": "session",
        "terminal": True,
        "effects": {
            "durable": False,
        },
    },
    {
        "id": "secret_whole_claim",
        "when": {
            "contains_secret": True,
            "redacted_non_empty": False,
        },
        "action": "drop",
        "terminal": True,
        "effects": {},
    },
    {
        "id": "secret_redacted",
        "when": {
            "contains_secret": True,
            "redacted_non_empty": True,
        },
        "action": None,
        "terminal": False,
        "effects": {
            "replace_text_with_redacted": True,
            "clear_evidence": True,
        },
    },
    {
        "id": "instruction_shaped",
        "when": {
            "looks_like_instruction": True,
        },
        "action": "flag",
        "terminal": True,
        "effects": {
            "flagged": True,
        },
    },
    {
        "id": "clean_non_user",
        "when": {
            "non_user": True,
        },
        "action": "session",
        "terminal": True,
        "effects": {
            "durable": False,
        },
    },
    {
        "id": "clean_user",
        "when": {},
        "action": "admit",
        "terminal": True,
        "effects": {},
    },
]

AUDIT_OPS: list[str] = [
    "add",
    "replace",
    "retire",
    "remove",
    "confirm",
    "reject",
    "undo",
    "archive",
    "restore",
]

AUDIT_OPS_DEFERRED: list[str] = [
    "archive",
    "restore",
]

AUDIT_STORES: list[str] = [
    "durable",
    "pending",
    "rejected",
]

AUDIT_ENTRY_FIELDS: list[dict[str, Any]] = [
    {
        "name": "seq",
        "type": "int",
        "required": True,
        "port": "yes",
    },
    {
        "name": "at",
        "type": "string",
        "required": True,
        "port": "yes",
    },
    {
        "name": "op",
        "type": "AuditOp",
        "required": True,
        "port": "yes",
    },
    {
        "name": "factId",
        "type": "string",
        "required": True,
        "port": "yes",
    },
    {
        "name": "before",
        "type": "UserFact",
        "required": False,
        "port": "yes",
    },
    {
        "name": "after",
        "type": "UserFact",
        "required": False,
        "port": "yes",
    },
    {
        "name": "store",
        "type": "AuditStore",
        "required": True,
        "port": "yes",
    },
    {
        "name": "writer",
        "type": "string",
        "required": True,
        "port": "yes",
    },
    {
        "name": "turn",
        "type": "string",
        "required": True,
        "port": "yes",
    },
    {
        "name": "undoes",
        "type": "int",
        "required": False,
        "port": "yes",
    },
    {
        "name": "erased",
        "type": "boolean",
        "required": False,
        "port": "deferred",
    },
    {
        "name": "group",
        "type": "string",
        "required": False,
        "port": "deferred",
    },
    {
        "name": "index",
        "type": "int",
        "required": False,
        "port": "yes",
    },
]

UNDO_MESSAGES: dict[str, str] = {
    "unknown_seq": "No audit entry #{seq}.",
    "is_undo": "Entry #{seq} is itself an undo.",
    "already_undone": "Entry #{seq} was already undone.",
    "erased": "Entry #{seq} was erased from history and cannot be restored.",
    "grouped": "Entry #{seq} belongs to a group; undoing grouped entries is not supported in this runtime.",
    "success": "Undid #{seq} ({op}): {text}",
}

UNDO_MESSAGES_PYTHON_ONLY: list[str] = [
    "grouped",
]

INV16: dict[str, Any] = {
    "knowledge_tiers": [
        "semantic",
        "identity",
        "preference",
    ],
    "non_user_origin_tier": "episodic",
    "never_promotable": [
        "agent",
        "tool",
        "web",
    ],
    "never_returned_tiers": [
        "procedural",
        "commitment",
    ],
}
