"""
Its Harness — reasoning and control architecture modules.

Phase 0 exports: core data structures and staleness infrastructure.
Phase 1 exports: evidence data model, tool reliability envelopes,
                 tool availability manifest, hypothesis generation and
                 elimination, canvas node compilers.
Phase 2 exports: belief dependency graph, belief propagation, contradiction
                 detection and resolution, staleness sweep, world model ops.
Phase 3 exports: diagnostic health vectors, normalisation contract,
                 ControlState, resolve_control_state, deadlock detection,
                 full gate implementations, main loop skeleton.
Phase 4 exports: task graph (P4.1), conflict probability cache (P4.2),
                 parallel branch merge (P4.3), abstraction fit check (P4.4).
Phase 5 exports: risk estimation (P5.1), VOI & adequacy critic (P5.2),
                 review gate (P5.3), execution engine (P5.4),
                 verification layer runner (P5.5).
Phase 6 exports: stall detection (P6.1), recovery strategies (P6.2),
                 failure mode library (P6.3), local/global replanning (P6.4),
                 context compression (P6.5), journal retention + max_steps (P6.6).
Phase 7 exports: external update poll (P7.1), constraint change propagation
                 (P7.2), escalation with surface_blocker (P7.3).
Phase 8 exports: experience store data model (P8.1), warm_start (P8.2),
                 update_experience_store (P8.3), adaptive strategy policy (P8.4).
"""

from .belief_graph import (
    BeliefDepGraph,
    BeliefEdge,
    DepGraphBudget,
    apply_decay,
    compute_dep_graph_quality,
    propagate_beliefs,
    propagate_single_update,
)
from .caller_state import CallerState, inject_clarification, reset_constraints_changed, update_success_criteria
from .constraint_propagation import apply_constraint_change_propagation, revalidate_task_graph
from .contradiction import (
    apply_resolution_policy,
    assign_system_breaking_severity,
    detect_abstraction_contradictions,
    detect_contradictions,
    detect_pairwise_contradictions,
    detect_set_level_contradictions,
    detect_temporal_contradictions,
)
from .control_state import (
    BlockEntry,
    ControlState,
    RiskState,
    compute_elevation_factor,
    detect_deadlock,
    resolve_control_state,
)
from .diagnostics import (
    BeliefHealth,
    CoverageHealth,
    Diagnostics,
    DimensionType,
    ExecutionHealth,
    NormalisationError,
    VerificationHealth,
    assert_normalised,
    normalise,
    normalise_entropy,
    update_diagnostics,
)
from .escalation import EscalationHalt, SurfaceBlocker, await_clarification, escalate
from .evidence import Evidence, EvidenceStore, EvidenceType, ReliabilityClass
from .execution import (
    ExecutionResult,
    ReversibilityStrategy,
    action_dep_overlap,
    execute,
    select_reversibility_strategy,
)

# Phase 8
from .experience_store import (
    DEFAULT_STRATEGY_ORDER,
    ExecutionContext,
    ExperienceEntry,
    ExperienceStore,
    ExperienceType,
    StrategyWeightKey,
    WarmStartResult,
    build_strategy_ordering,
    load_strategy_priors,
    load_structural_decompositions,
    load_tool_workflow_seeds,
    load_verification_plan_seeds,
    softmax_strategy_policy,
    update_experience_store,
    upsert_strategy_weight,
    warm_start,
)
from .external_updates import (
    NoOpUpdateChannel,
    PendingUpdate,
    PostgresNotifyChannel,
    UpdateChannel,
    check_external_updates,
)
from .failure_modes import (
    FailureDiagnostics,
    FailureEntry,
    FailureModeLibrary,
    FailurePattern,
    MatchResult,
    build_default_library,
    normalise_confidence,
)
from .gates import StalenessError, action_gate, decomposition_gate, post_exec_gate
from .hypothesis import (
    EliminationPolicy,
    EliminationRecord,
    Hypothesis,
    HypothesisSet,
    analogy_based_generation,
    check_contradicting_evidence,
    check_posterior_floor,
    check_prediction_failure,
    compute_diversity_score,
    counterfactual_reasoning,
    eliminate,
    enforce_diversity,
    failure_mode_library_contribution,
    generate_from_failure_library,
    generate_hypotheses,
    symptom_inference,
)

# Phase 11
from .langfuse_tracing import (
    HarnessTraceContext,
    emit_escalation_event,  # noqa: F401
    emit_iteration_span,  # noqa: F401
    emit_strategy_change_event,  # noqa: F401
)
from .loop import initialize_harness, run_one_iteration, select_best_action
from .memory import (
    CompressionRisk,
    MemoryState,
    PrunedRegion,
    Structure,
    apply_retention_policy,
    check_max_steps,
    compress_memory,
    should_compress,
)
from .node_compilers import (
    HARNESS_NODE_COMPILERS,
    compile_apply_tool_reliability,
    compile_control_state_node,
    compile_evidence_store_node,
    compile_experience_store_node,
    compile_gather_evidence,
    compile_hypothesis_set_node,
    compile_recovery_node,
    compile_reviewer_pass_node,
    compile_task_graph_node,
    compile_update_world_model,
    compile_verification_gate_node,
    compile_world_model_node,
)
from .output_contract import (
    ContractCheckResult,
    OutputContract,
    check_caller_specific_constraints,
    check_format_requirements,
    check_interface_constraints,
    check_required_sections,
    completion_check_final,
    contract_shadow_check,
    update_output_contract,
    validate_output_contract,
)
from .parallel_merge import merge_world_models, reconcile_parallel_branches
from .process_concept import (
    ProcessConcept,
    ProcessConceptNotFoundError,
    ProcessConceptStep,
    ProcessConceptValidationError,
)
from .process_registry import DEFAULT_REGISTRY, ProcessRegistry
from .process_tools import complete_step, get_current_step, list_processes, load_process
from .progress import (
    cannot_make_progress,
)
from .recovery import (
    STRATEGY_ORDER,
    StrategyState,
    StrategyType,
    apply_failure_mode_bias,
    get_next_strategy,
    get_strategy_with_experience,
    switch_strategy,
)
from .replanning import (
    ReplanScope,
    apply_replan,
    assess_replan_scope,
    diagnose_and_replan,
    rebuild_task_graph,
)
from .review_gate import (
    DimensionResult,
    ReviewResult,
    check_code_quality,
    check_hypothesis_compatibility,
    check_output_contract,
    check_task_alignment,
    check_world_model_consistency,
    review_proposed_change,
)

# Phase 9
from .reviewer import (
    AdversarialPrior,
    ReviewFinding,
    ReviewPassResult,
    compute_causal_proximity,
    drain_propagation_queue,
    reviewer_pass,
    seed_adversarial_prior,
)

# Phase 5
from .risk import (
    RiskFactors,
    RiskLevel,
    classify_module_type,
    compute_change_scope,
    compute_file_centrality,
    estimate_risk,
)
from .staleness import assert_generation_fresh, increment_generation_id, staleness_check, staleness_sweep
from .state_store import HarnessRunState
from .task_graph import (
    ConflictProbabilityCache,
    Task,
    TaskGraph,
    TaskRisk,
    TaskStatus,
    check_abstraction_alignment,
    compute_initial_conflict_probabilities,
    record_actual_overlap,
    select_unblocked_leaf,
    should_use_pessimistic_blocking,
    update_from_experience_store,
    validate_task_graph,
)
from .tool_manifest import (
    FrozenManifestError,
    ToolAvailabilityManifest,
    ToolEntry,
    build_manifest,
)
from .tool_reliability import (
    TOOL_RELIABILITY_ENVELOPES,
    ToolEnvelope,
    apply_tool_reliability_envelope,
    get_envelope,
)
from .verification import (
    LayerResult,
    VerificationLayer,
    VerificationResult,
    verify,
    verify_assumptions,
    verify_consistency,
    verify_evidence_sufficiency,
    verify_goal_correctness,
    verify_integration,
    verify_output_contract_partial,
    verify_requirements,
    verify_syntax,
    verify_unit,
)
from .voi import (
    AdequacyResult,
    VOIResult,
    estimate_value_of_information,
    update_verification_strength,
    verification_adequacy_critic,
)
from .world_model import Belief, Contradiction, Observation, WorldModel
from .world_model_ops import integrate_evidence, recompute_belief_health

__all__ = [
    "DEFAULT_REGISTRY",
    "DEFAULT_STRATEGY_ORDER",
    "HARNESS_NODE_COMPILERS",
    "STRATEGY_ORDER",
    "TOOL_RELIABILITY_ENVELOPES",
    "AdequacyResult",
    "AdversarialPrior",
    "Belief",
    "BeliefDepGraph",
    "BeliefEdge",
    "BeliefHealth",
    "BlockEntry",
    "CallerState",
    "CompressionRisk",
    "ConflictProbabilityCache",
    "ContractCheckResult",
    "Contradiction",
    "ControlState",
    "CoverageHealth",
    "DepGraphBudget",
    "Diagnostics",
    "DimensionResult",
    "DimensionType",
    "EliminationPolicy",
    "EliminationRecord",
    "EscalationHalt",
    "Evidence",
    "EvidenceStore",
    "EvidenceType",
    "ExecutionContext",
    "ExecutionHealth",
    "ExecutionResult",
    "ExperienceEntry",
    "ExperienceStore",
    "ExperienceType",
    "FailureDiagnostics",
    "FailureEntry",
    "FailureModeLibrary",
    "FailurePattern",
    "FrozenManifestError",
    "HarnessRunState",
    "HarnessTraceContext",
    "Hypothesis",
    "HypothesisSet",
    "LayerResult",
    "MatchResult",
    "MemoryState",
    "NoOpUpdateChannel",
    "NormalisationError",
    "Observation",
    "OutputContract",
    "PendingUpdate",
    "PostgresNotifyChannel",
    "ProcessConcept",
    "ProcessConceptNotFoundError",
    "ProcessConceptStep",
    "ProcessConceptValidationError",
    "ProcessRegistry",
    "PrunedRegion",
    "ReliabilityClass",
    "ReplanScope",
    "ReversibilityStrategy",
    "ReviewFinding",
    "ReviewPassResult",
    "ReviewResult",
    "RiskFactors",
    "RiskLevel",
    "RiskState",
    "StalenessError",
    "StrategyState",
    "StrategyType",
    "StrategyWeightKey",
    "Structure",
    "SurfaceBlocker",
    "Task",
    "TaskGraph",
    "TaskRisk",
    "TaskStatus",
    "ToolAvailabilityManifest",
    "ToolEntry",
    "ToolEnvelope",
    "UpdateChannel",
    "VOIResult",
    "VerificationHealth",
    "VerificationLayer",
    "VerificationResult",
    "WarmStartResult",
    "WorldModel",
    "action_dep_overlap",
    "action_gate",
    "analogy_based_generation",
    "apply_constraint_change_propagation",
    "apply_decay",
    "apply_failure_mode_bias",
    "apply_replan",
    "apply_resolution_policy",
    "apply_retention_policy",
    "apply_tool_reliability_envelope",
    "assert_generation_fresh",
    "assert_normalised",
    "assess_replan_scope",
    "assign_system_breaking_severity",
    "await_clarification",
    "build_default_library",
    "build_manifest",
    "build_strategy_ordering",
    "cannot_make_progress",
    "check_abstraction_alignment",
    "check_caller_specific_constraints",
    "check_code_quality",
    "check_contradicting_evidence",
    "check_external_updates",
    "check_format_requirements",
    "check_hypothesis_compatibility",
    "check_interface_constraints",
    "check_max_steps",
    "check_output_contract",
    "check_posterior_floor",
    "check_prediction_failure",
    "check_required_sections",
    "check_task_alignment",
    "check_world_model_consistency",
    "classify_module_type",
    "compile_apply_tool_reliability",
    "compile_control_state_node",
    "compile_evidence_store_node",
    "compile_experience_store_node",
    "compile_gather_evidence",
    "compile_hypothesis_set_node",
    "compile_recovery_node",
    "compile_reviewer_pass_node",
    "compile_task_graph_node",
    "compile_update_world_model",
    "compile_verification_gate_node",
    "compile_world_model_node",
    "complete_step",
    "completion_check_final",
    "compress_memory",
    "compute_causal_proximity",
    "compute_change_scope",
    "compute_dep_graph_quality",
    "compute_diversity_score",
    "compute_elevation_factor",
    "compute_file_centrality",
    "compute_initial_conflict_probabilities",
    "contract_shadow_check",
    "counterfactual_reasoning",
    "decomposition_gate",
    "detect_abstraction_contradictions",
    "detect_contradictions",
    "detect_deadlock",
    "detect_pairwise_contradictions",
    "detect_set_level_contradictions",
    "detect_temporal_contradictions",
    "diagnose_and_replan",
    "drain_propagation_queue",
    "eliminate",
    "enforce_diversity",
    "escalate",
    "estimate_risk",
    "estimate_value_of_information",
    "execute",
    "failure_mode_library_contribution",
    "generate_from_failure_library",
    "generate_hypotheses",
    "get_current_step",
    "get_envelope",
    "get_next_strategy",
    "get_strategy_with_experience",
    "increment_generation_id",
    "initialize_harness",
    "inject_clarification",
    "integrate_evidence",
    "list_processes",
    "load_process",
    "load_strategy_priors",
    "load_structural_decompositions",
    "load_tool_workflow_seeds",
    "load_verification_plan_seeds",
    "merge_world_models",
    "normalise",
    "normalise_confidence",
    "normalise_entropy",
    "post_exec_gate",
    "propagate_beliefs",
    "propagate_single_update",
    "rebuild_task_graph",
    "recompute_belief_health",
    "reconcile_parallel_branches",
    "record_actual_overlap",
    "reset_constraints_changed",
    "resolve_control_state",
    "revalidate_task_graph",
    "review_proposed_change",
    "reviewer_pass",
    "run_one_iteration",
    "seed_adversarial_prior",
    "select_best_action",
    "select_reversibility_strategy",
    "select_unblocked_leaf",
    "should_compress",
    "should_use_pessimistic_blocking",
    "softmax_strategy_policy",
    "staleness_check",
    "staleness_sweep",
    "switch_strategy",
    "symptom_inference",
    "update_diagnostics",
    "update_experience_store",
    "update_from_experience_store",
    "update_output_contract",
    "update_success_criteria",
    "update_verification_strength",
    "upsert_strategy_weight",
    "validate_output_contract",
    "validate_task_graph",
    "verification_adequacy_critic",
    "verify",
    "verify_assumptions",
    "verify_consistency",
    "verify_evidence_sufficiency",
    "verify_goal_correctness",
    "verify_integration",
    "verify_output_contract_partial",
    "verify_requirements",
    "verify_syntax",
    "verify_unit",
    "warm_start",
]
